trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CMake@1
  inputs:
    workingDirectory: build
    cmakeArgs: ..

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: build
    artifactName: dfa-cli
