trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CMake@1
  inputs:
    workingDirectory: 'build'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/build
    artifactName: dfa-cli
